### PR TITLE
Generator: Next

### PR DESCRIPTION
**Pull request by blackfalcon**
# Alaska Airlines Pull Request

This PR is a summary of multiple open issues in preparation for the next release. See individual issues for item details. 

**Fixes:** See https://github.com/AlaskaAirlines/WC-Generator/pull/79/commits comments for references to closed issues

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [x] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by blackfalcon** [comment]
@jason-capsule42 why did you close this PR?

**Comment by jason-capsule42** [comment]
I have no idea how this got closed... reopening it.

**Comment by blackfalcon** [comment]
@geoffrich @jason-capsule42 I have completed a full review and have closed out all the remaining PRs and Issues that were associated with this release. 

We are ready to 🚀 if I could get one of your's blessings.

**Review by geoffrich — APPROVED** [review]

**Pull request merged**
