### PR TITLE
Jbaker/static docs

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Summary:

This change adds a directory of document parts that will be consumed in a future PR. All content in these parts exists already in component documentation and has been unchanged beyond splitting into parts.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [x] Other (static documents)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by blackfalcon — CHANGES_REQUESTED** [review]
`./template/README__labs.md` needs to be removed. 

Outside of that, this is approved for release.

**Comment by jason-capsule42** [comment]
> `./template/README__labs.md` needs to be removed.
> 
> Outside of that, this is approved for release.

This will get removed when the static docs are actually used to build the readme. For the time being, this PR alone would cause a break in the generator script if that file were to be removed.

**Comment by jason-capsule42** [comment]
Merging this manually per comment approval from @blackfalcon.

**Pull request merged**
